### ISSUE TITLE
This template does not work well with 1.11.0-rc2

### ISSUE THREAD

**Issue by MFYDev** [TylerByte666/gitea-matrix-template#1]
Hi there,

Thank you so much for your excellent work and hard working first.

But I just try this one on gitea 1.11.0-rc2 and it broke my Gitea down.

Every elements on the page became unordered and some of them cannot even display.

Would you please do some check? Thank you so mcuh!

**Comment by TylerByte666** [comment]
Hi, still need to upload the rest of the code and README.MD

Will do tonight.

**Comment by TylerByte666** [comment]
Code complete. Please check the README.md

**Comment by MFYDev** [comment]
Thank you for the update.

Actually it still not works well with Gitea 1.11.0-rc2

Cause in this version Gitea made some changes on the templates.....

Would you please have some check?

I would so much appreciate that....

![捕获](https://user-images.githubusercontent.com/53750381/73709762-f0b19080-473c-11ea-803d-77e2e3d8e9f1.PNG)

**Comment by 6543** [comment]
@FanyangMengDev https://github.com/6543-forks/gitea-matrix-template/tree/gitea_v1.11.x does ...
@TylerByte666 I'll send Pull if other's are merged ...
(you can work with different branches for different gitea versions ...)

**Comment by MFYDev** [comment]
@6543 Bravo mate! You are really excellent !!

**Comment by MFYDev** [comment]
@6543 Hi mate, I just use the theme after you customization and it works well finally! : )

But there are two places that I think maybe it needs some enhancement.

1. Sign in page.
![2](https://user-images.githubusercontent.com/53750381/73751377-f4bfcb80-4799-11ea-94b5-0b79363f00de.PNG)

2. Repo list
![1](https://user-images.githubusercontent.com/53750381/73751399-ff7a6080-4799-11ea-93e3-dc127425949f.PNG)

3. Explore page
![3](https://user-images.githubusercontent.com/53750381/73752470-fee2c980-479b-11ea-878b-d30642ba6a94.PNG)
You can see that the color of description of the repo is same as the backgroud.

All these happens because @TylerByte666 use arc-green as default so when we use it as default the font color will fit the theme. But when use the Matrix theme. It needs some changes actually.

I really wanna do it by myself but unfortunately I am really a frontend noob....

**Comment by 6543** [comment]
@FanyangMengDev the easyest way is to base the theme on the arc-green ...
I'll have a look at it

**Comment by 6543** [comment]
@FanyangMengDev updated ... now arc-green is base theme
but I think it need a bit more work ... f49649be9fa689cfed6575266b9ea6d536d6899d

**Comment by 6543** [comment]
@TylerByte666 arc-green use is a less file witch is compiled to css ... I thing a good way would be to copy the less file and then modify it to the needs ...

**Comment by MFYDev** [comment]
@6543 Just finish learning how to customize css. And I have done some of it. You are right. There are so much work need to be done on css file.

Just did my best to do some customization on yours, now this is like the following:
![6](https://user-images.githubusercontent.com/53750381/73761236-87b43200-47a9-11ea-812e-1d452f87eeea.PNG)
![7](https://user-images.githubusercontent.com/53750381/73761245-8b47b900-47a9-11ea-9766-02e6d87205bc.PNG)
![8](https://user-images.githubusercontent.com/53750381/73761246-8b47b900-47a9-11ea-961a-75847fae9545.PNG)
![9](https://user-images.githubusercontent.com/53750381/73761248-8be04f80-47a9-11ea-92f9-13ece43863ef.PNG)

**Comment by MFYDev** [comment]
@6543 I will make a pull request after my work done. Have to admit that is not the best looking, but it is more matrix than before at least.....

**Comment by MFYDev** [comment]
@6543 Oh, by the way, really have a question on customization. Did you have to change the css file name after you finish customizing the css file and change the css name in head.tmpl every time after you restart the gitea?

Here is what I meet. Every time I finish changing the css file, just restart the gitea will not see the changes. I have to change the css file name and change its name in head.tmpl at the same time, then restart the Gitea, only in this way the changes will work. 

I tried to clear my browser's cache and cdn's cache, but without changing the file name nothing will work.....

This problem already made me change the theme-matrix.css to theme-matrix10.css.
Really drives me crazy and wanna know how to fix it.

If you know how to fix it would you please tell me?

Thank you in advance.

**Comment by 6543** [comment]
@FanyangMengDev do you use Chrome?

**Comment by MFYDev** [comment]
@6543 Yes, it is Chrome

**Comment by 6543** [comment]
@FanyangMengDev Chrome is bad about forgetting things :D - eave if you tell to delete the cache ...

-> Use Firefox if you clear the cache on and you can reload with new css

**Comment by MFYDev** [comment]
@6543 I see, thanks a lot sincerely. Always heard about that Firefox is the best browser to do frontend customization. I will install it now.

But what makes me most confused is that this problem does not only happens on PC Chrome. it happens on Android Chrome too. So as for your experience, is Android phone's Chrome also has this problem?

**Comment by 6543** [comment]
I dont use Chrome on Android :sweat_smile:

**Comment by MFYDev** [comment]
@6543 @TylerByte666 Done. Just finish the enhancement of the theme-matrix.css file.

Actually this is the first time I use Github....hence I really do not know how to make a pull request..... : (

So I will upload the css file to here.... I will learn how to make the request later because it is already 1am in Beijing....

Here is what it looks like after my customization...... Hope you like it : )
![8](https://user-images.githubusercontent.com/53750381/73767230-25abfa80-47b2-11ea-9298-5edd528413f0.PNG)
![1](https://user-images.githubusercontent.com/53750381/73767232-25abfa80-47b2-11ea-9dd0-432de368df07.PNG)
![2](https://user-images.githubusercontent.com/53750381/73767234-26449100-47b2-11ea-9898-71b849d02488.PNG)
![3](https://user-images.githubusercontent.com/53750381/73767235-26449100-47b2-11ea-8cd7-e4edc6c775fd.PNG)
![4](https://user-images.githubusercontent.com/53750381/73767236-26dd2780-47b2-11ea-8e60-66916bd9a390.PNG)
![5](https://user-images.githubusercontent.com/53750381/73767238-26dd2780-47b2-11ea-8fca-02e5e77e3802.PNG)
![6](https://user-images.githubusercontent.com/53750381/73767241-26dd2780-47b2-11ea-89b6-5c702b9fc85f.PNG)
![7](https://user-images.githubusercontent.com/53750381/73767242-2775be00-47b2-11ea-967f-f4bfb4264b15.PNG)

Here is the css file in the following:
[theme-matrix13.txt](https://github.com/TylerByte666/gitea-matrix-template/files/4154760/theme-matrix13.txt)

As you can see it has been the 13 version....

And I just tried on Firfox that problem still happenes....  I seriously think that is the Gitea's bug.

Hoping you can help me make it more good looking...

From a Github begginner..... : )

**Comment by TylerByte666** [comment]
Wow Guys! Nice work!

**Comment by TylerByte666** [comment]
I am blown away! And ready for more merges, when you get used to it @FanyangMengDev  👍 Closing the issue for now thanks to @6543 🥇
