### ISSUE TITLE
witch licence has this theme?

### ISSUE THREAD

**Issue by 6543** [TylerByte666/gitea-matrix-template#3]

**Comment by TylerByte666** [comment]
Hi Should be same as gitea: 

MIT License

A short and simple permissive license with conditions only requiring preservation of copyright and license notices. Licensed works, modifications, and larger works may be distributed under different terms and without source code.
Permissions

Commercial use:
Modification
Distribution
Private use

Limitations:
Liability
Warranty

**Comment by 6543** [comment]
good to know :+1: - just add the file in the root of the reop so everybody know what he is alowed to do :)
