### ISSUE TITLE
Finalizinh 1.10.x

### ISSUE THREAD

**Issue by 6543** [TylerByte666/gitea-matrix-template#9]
Since 1.11.0 is now publisched, we schould finisch changes for 1.10.x, create a tag/release and I'll send the changes for 1.11.x?

**Comment by 6543** [comment]
@TylerByte666 I'll do it tomorow if you dont have time :)

**Comment by MFYDev** [comment]
@6543 Of course, I think we need to do that. But I will have a meeting in the next few hours. I can learn how to do it and maybe finish this job before tommorrow night~ : )

**Comment by TylerByte666** [comment]
Hi my hardworking friends!!! Thanks for everything, I can do the tag and
also test tonight :)

**Comment by MFYDev** [comment]
@TylerByte666 Bravo mate! Thank you so much! : )

**Comment by 6543** [comment]
end result: https://github.com/TylerByte666/gitea-matrix-template/releases
